name: pandoc-crossref
version: '0.2.6.0'
synopsis: Pandoc filter for cross-references
description: pandoc-crossref is a pandoc filter for numbering figures, equations,
  tables and cross-references to them.
category: Text
author: Nikolay Yakimov
maintainer: root@livid.pp.ru
license: GPL-2
license-file: LICENSE.md
github: lierdakil/pandoc-crossref
dependencies:
  - base >=4.9 && <5
  - pandoc ==1.19.*
  - pandoc-types ==1.17.*
flags:
  static:
    manual: true
    default: false
  ld-gold:
    manual: true
    default: false
when:
  - condition: flag(ld-gold)
    then:
      ld-options:
        - -fuse-ld=gold
    else:
      ld-options:
        - -fuse-ld=bfd
  - condition: flag(static)
    ld-options:
      - -static
library:
  source-dirs: lib
  ghc-options:
  - -Wall
  exposed-modules:
  - Text.Pandoc.CrossRef
  dependencies:
  - mtl >=1.1 && <2.3
  - containers >=0.1 && <0.6
  - data-default >=0.4 && <0.8
  - data-accessor >=0.2.2.6 && <0.3.0.0
  - data-accessor-template >=0.2.1.12 && <0.3.0.0
  - data-accessor-transformers >=0.2.1.6 && <0.3.0.0
  - template-haskell >=2.7.0.0 && <3.0.0.0
  - roman-numerals ==0.5.*
  - syb >=0.4 && <0.8
  - utility-ht >=0.0.11 && <0.1.0
  - directory >=1 && <1.4
  - filepath >=1.1 && <1.5
executables:
  pandoc-crossref:
    main: pandoc-crossref.hs
    source-dirs: src
    ghc-options:
    - -Wall
    - -threaded
    dependencies:
    - pandoc-crossref
tests:
  test-pandoc-crossref:
    main: test-pandoc-crossref.hs
    source-dirs:
    - test
    - lib
    ghc-options:
    - -rtsopts
    - -Wall
    - -fno-warn-unused-do-bind
    - -threaded
    dependencies:
    - pandoc-crossref
    - hspec
    - mtl
    - containers
    - data-default
    - data-accessor-template
    - syb
    - roman-numerals
    - template-haskell
    - utility-ht
    - data-accessor
    - directory
    - filepath
    - data-accessor-transformers
  test-integrative:
    main: test-integrative.hs
    source-dirs: test
    ghc-options:
    - -rtsopts
    - -Wall
    - -fno-warn-unused-do-bind
    - -threaded
    dependencies:
    - hspec
    - filepath
    - directory
    - pandoc-crossref
data-files:
- demo.md
- test/m2m/*/*.md
- test/m2m/*/*.tex
extra-source-files:
- test/*.inc
