name: pandoc-crossref
version: '0.3.0.1'
synopsis: Pandoc filter for cross-references
description: pandoc-crossref is a pandoc filter for numbering figures, equations,
  tables and cross-references to them.
category: Text
author: Nikolay Yakimov
maintainer: root@livid.pp.ru
license: GPL
license-file: LICENSE
github: lierdakil/pandoc-crossref
extra-source-files:
- test/*.inc
data-files:
- docs/demo/demo.md
- docs/index.md
- test/m2m/*/*
dependencies:
- base >=4.9 && <5
- pandoc ==2.0.*
- pandoc-types ==1.17.*
- mtl >=1.1 && <2.3
- containers >=0.1 && <0.6
- data-default >=0.4 && <0.8
- data-accessor >=0.2.2.6 && <0.3.0.0
- data-accessor-template >=0.2.1.12 && <0.3.0.0
- data-accessor-transformers >=0.2.1.6 && <0.3.0.0
- template-haskell >=2.7.0.0 && <3.0.0.0
- roman-numerals ==0.5.*
- syb >=0.4 && <0.8
- utility-ht >=0.0.11 && <0.1.0
- directory >=1 && <1.4
- filepath >=1.1 && <1.5
- text >=1.2.2 && <1.3
library:
  source-dirs: lib
  ghc-options: 
  - -Wall 
  - -threaded
  exposed-modules:
  - Text.Pandoc.CrossRef
executables:
  pandoc-crossref:
    main: pandoc-crossref.hs
    source-dirs: src
    ghc-options: 
    - -Wall 
    - -threaded
    dependencies:
    - pandoc-crossref
    - optparse-applicative >= 0.13 && < 0.15
    - open-browser >= 0.2 && < 0.3
    - temporary >= 1.2 && < 1.3
    - deepseq >= 1.4 && < 1.5
tests:
  test-pandoc-crossref:
    main: test-pandoc-crossref.hs
    source-dirs:
    - test
    - lib
    ghc-options:
    - -Wall
    - -fno-warn-unused-do-bind
    - -threaded
    dependencies:
      - hspec >=2.4.4 && <3
  test-integrative:
    main: test-integrative.hs
    other-modules: []
    source-dirs: test
    ghc-options:
    - -Wall
    - -fno-warn-unused-do-bind
    - -threaded
    dependencies:
    - pandoc-crossref
    - hspec >=2.4.4 && <3
